# Generated by Django 4.0.7 on 2022-08-16 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'ordering': ['-broadcast_on']},
        ),
        migrations.RemoveField(
            model_name='emailnotification',
            name='title',
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='broadcast_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
